# Generated by Django 2.2.12 on 2021-01-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
    ]
