# Generated by Django 2.2.12 on 2021-01-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=56.5, max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=60.6, max_length=10),
        ),
    ]
