# Generated by Django 2.2.12 on 2021-01-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0004_auto_20210108_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, default=56.5, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, default=60.6, max_length=10, null=True),
        ),
    ]
