# Generated by Django 2.2.12 on 2021-01-09 10:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0005_auto_20210108_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
        migrations.AddField(
            model_name='post',
            name='lngLat',
            field=jsonfield.fields.JSONField(blank=True, default='', null=True),
        ),
    ]
