# Generated by Django 2.2.12 on 2021-01-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0007_auto_20210109_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
    ]
