# Generated by Django 2.2.12 on 2021-01-09 11:59

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0008_remove_post_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=geoposition.fields.GeopositionField(default='', max_length=42),
        ),
    ]
