# Generated by Django 2.2.12 on 2021-01-10 09:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0009_post_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='position',
        ),
        migrations.AddField(
            model_name='post',
            name='lngLat',
            field=jsonfield.fields.JSONField(blank=True, default='', null=True),
        ),
    ]
