# Generated by Django 2.2.12 on 2021-01-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0010_auto_20210110_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lngLat',
        ),
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.FloatField(blank=True, default=0.0, max_length=10, null=True),
        ),
    ]
