# Generated by Django 2.2.12 on 2021-01-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0011_auto_20210110_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=20),
        ),
    ]
